services:
  python:
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
    volumes:
      - .:/code
    depends_on:
      - postgres
    # entrypoint: Do nothing for now
    entrypoint: tail -f /dev/null

  postgres:
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${IMPERIAL_POLICE_2_POSTGRES_USER}
      POSTGRES_PASSWORD: ${IMPERIAL_POLICE_2_POSTGRES_PASSWORD}

volumes:
  postgres_data:

networks:
  default:
    name: imperial_police_2
    enable_ipv6: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
          ip_range: 172.28.5.0/24
          gateway: 172.28.5.254
        - subnet: 2001:3200:3200::/64
          gateway: 2001:3200:3200::1
