services:
  python:
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
    volumes:
      # Not to mount .venv directory, separate the directory as a volume
      - python_venv:/workspace/.venv
      - .:/workspace
    networks:
      - backend
    depends_on:
      - postgres
    # entrypoint: Do nothing for now
    command: tail -f /dev/null
    restart: unless-stopped
    tty: true

  postgres:
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    ports:
      - "54321:5432"
    environment:
      POSTGRES_USER: ${IMPERIAL_POLICE_2_POSTGRES_USER}
      POSTGRES_PASSWORD: ${IMPERIAL_POLICE_2_POSTGRES_PASSWORD}
    restart: unless-stopped
    tty: true

volumes:
  python_venv:
    driver: local
  postgres_data:
    driver: local

networks:
  backend:
    name: imperial_police_2
    enable_ipv6: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
          ip_range: 172.28.5.0/24
          gateway: 172.28.5.254
        - subnet: 2001:3200:3200::/64
          gateway: 2001:3200:3200::1
